### ISSUE TITLE
bug: Failed to render doc template dbml.j2

### ISSUE THREAD

**Issue by sarim-zafar** [foliant-docs/docs#35]
I am using the following command for a fairly sophisticated dbml. I've ensured there is no circular dependency and i am running this through a docker on m1 pro macbook. I've also tried through mkdocs and it gives me the same error.
`docker-compose run --rm foliant make site --with slate`
```
Failed to render doc template dbml.j2
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/foliant/preprocessors/dbmldoc/dbmldoc.py", line 107, in _process_jinja
    result += template.render(data=data)

  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()

  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)

  File "dbml.j2", line 70, in top-level template code
    {{ render_table(table, data) }}

  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)

  File "dbml.j2", line 46, in template
    {{ render_table_ref(ref, col) }}

  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)

  File "dbml.j2", line 14, in template
    {%- if ref_col == col %} [{{ ref.table1.name}}](#{{ref.table1.name.lower()}}).(

  File "/usr/local/lib/python3.8/dist-packages/pydbml/classes/base.py", line 37, in __eq__
    return self.__dict__ == other.__dict__

  File "/usr/local/lib/python3.8/dist-packages/pydbml/classes/base.py", line 37, in __eq__
    return self.__dict__ == other.__dict__

  File "/usr/local/lib/python3.8/dist-packages/pydbml/classes/base.py", line 37, in __eq__
    return self.__dict__ == other.__dict__

  [Previous line repeated 322 more times]

RecursionError: maximum recursion depth exceeded

```

**Comment by sarim-zafar** [comment]
Turns out there was a small logical error in my dbml file
